# -*- coding: utf-8 -*-
"""Moda - Semana13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12DVVEKStpTv99qZ2xFvyTgCEqEap5tAD

# EJERCICIO DE MODA - SEMANA 13
En una empresa de comercialización, se tiene una data que corresponde a la lista de clientes. Vamos a analizar la edad de los clientes más frecuentes que vienen a comprar productos.
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, expr, mean, corr
spark = SparkSession.builder.appName("Moda-Semana13").getOrCreate()
spark

archivo = spark.read.csv("moda.csv", header=True, inferSchema=True, sep=";")
archivo.show()

var_moda = archivo.groupBy("Edad").count().orderBy(col("count").desc()).first()

print("La edad de los clientes más frecuentes es: ", var_moda["Edad"])