# -*- coding: utf-8 -*-
"""Media-Semana13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19WA-xbxY3ZltNjemr9EAD3FQDnE3cVcW

# EJERCICIO DE MEDIA - SEMANA 13
En una empresa de comercialización, se tiene una data que corresponde a la lista de clientes con su edad. Vamos a analizar media de la edad de los clientes según un archivo CSV utilizando su edad. Con esta información podremos entender mejor la clientela y aplicar algunas estrategias de marketing y ventas.
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, expr, mean, corr
spark = SparkSession.builder.appName("Media-Semana13").getOrCreate()
spark

archivo = spark.read.csv("media.csv", header=True, inferSchema=True, sep=";")
archivo.show()

var_media = archivo.select(mean(col("Edad")).alias("Media")).collect()[0]["Media"]
print(f"La media de la edad de los clientes es: {var_media}")