# -*- coding: utf-8 -*-
"""Mediana.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tgoZepj7kmng6E1tyF-kdoqcsxmHoBWE

# EJERCICIO DE MEDIANA - SEMANA 13
En una empresa de comercialización, se tiene una data que corresponde a la lista de clientes. Ahora analizaremos la mediana y con ello sacaremos conclusiones de nuestra clientela, y hallar el valor central de todas las edades registradas.
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, expr, mean, corr
spark = SparkSession.builder.appName("Mediana-Semana13").getOrCreate()
spark

archivo = spark.read.csv("mediana.csv", header=True, inferSchema=True, sep=";")
archivo.show()

var_mediana = archivo.approxQuantile("Edad",[0.5],0.0)
print("La mediana de nuestros clientes registrados por compras es: ",var_mediana)