# -*- coding: utf-8 -*-
"""Correlacion-Semana13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mz1-SczBjipr0RwxoijSoxGW-eOA2oG0

# EJERCICIO DE CORRELACION - SEMANA 13
En una empresa de comercialización, se tiene una data que corresponde a la encuesta realizada a los clientes acerca de su satisfacción y frecuencia de compras en la empresa. Ahora analizaremos la correlacion a partir de un archivo CSV.
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, expr, mean, corr
spark = SparkSession.builder.appName("Mediana-Semana13").getOrCreate()
spark

archivo = spark.read.csv("correlacion.csv", header=True, inferSchema=True, sep=";")
archivo.show()

correlacion = archivo.select(corr(col("Satisfaccion del cliente"),col("Frecuencia de compra")).alias("correlacion")).collect()[0]["correlacion"]
print("La correlación de nuestra clientela es: ",correlacion)